version: "3"
services:
  db:
    image: mysql:5.7
    container_name: db
    command: mysqld --sql_mode=""
    environment:
      MYSQL_DATABASE: 'bd'
      MYSQL_USER: app
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 42333:3306
    networks:
      - local
  web:
    image: myphp
    container_name: app
    working_dir: /app
    command: php7.4 -S 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 80:8000
    depends_on:
      - db
    networks:
      - local
networks: 
  local:
    driver: bridge
